# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObjectDetectionAI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjectDetectionAI

pod 'TensorFlowLiteSwift'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'


end
